### ISSUE TITLE
When downloading a file, error: "Cannot return null or undefined from an endpoint"

### ISSUE THREAD

**Issue by andrewash** [kahmali/meteor-restivus#135]
Thank you for putting this awesome library together!
I've created a custom "get" endpoint for one of my collections. This endpoint responds by writing an (MP3) file in the response and sending it to the client. Only authenticated responses are accepted (the security trimming is why I'm using Restivus for this, instead of regular HTTP download).

It works, but generates an error in Meteor's server console:
```
 Error: Cannot return null or undefined from an endpoint: get api/recordings/:id
     at packages/nimble:restivus/lib/route.coffee:61:25
     at packages/simple:json-routes/json-routes.js:45:1
```

I am calling this.done(), per the docs, so I'm not sure why the error occurs.

Anything I can do to eliminate the error message?

Thanks for your help,
Andrew

```
// Generates: GET on /api/recordings
API.addCollection(Recordings, {
  excludedEndpoints: ['post', 'put', 'delete'],
  routeOptions: {
    authRequired: true,
    roleRequired: ['student', 'teacher']
  },
  endpoints: {
    get: {
      action: function() {
        // GET api/recordings/:id
        // tested with: wget --content-disposition http://localhost:3000/api/recordings/NaxN2DLQThpaH4k7Z
        // this saves the file with the correct filename
        if (!this.urlParams.id) {
         return {
           statusCode: 400,
           body: {
             status: "failure",
             message: "Missing Recording ID"
           }
         };
        }                
        // Construct the query
        var permissionsFilter = API.buildQueryFilterForPermittedRecordings(this.userId);
        var recordingId = this.urlParams.id;
        var query = {$and: [permissionsFilter, {_id: recordingId}]};
        var recording = Recordings.findOne(query);
        if (!recording) {
         return {
           statusCode: 400,
           body: {
             status: "failure",
             message: "Invalid Recording ID"
           }
         };
        }

        var destFilename = Recordings.buildFilename(recording);
        var filePath = process.env.PWD + recording.url;
        var data = fs.readFileSync(filePath);            
        this.response.writeHead(200, {
          'Content-disposition': "attachment; filename=" + destFilename,
          'Content-type': 'audio/mpeg3',
          'Content-length': data.length
        });        
        this.response.write(data);
        this.done();
      }
    }
  }
});
```

**Comment by kahmali** [comment]
Everything looks great there at first glance. This is a tested feature, so, if you're experiencing a potential bug, I'll either need reproduction steps or (even better) a sample repo demonstrating the issue. That should help me get to the bottom of it. Sorry that you're experiencing the issue. I hope we can get this resolved for you asap.  Also, thanks for the compliment, and thanks for reporting this!

**Comment by mehar** [comment]
Returning an empty object saved me from the same exception!!

**Comment by kahmali** [comment]
@mehar Thanks for the suggestion. The problem here is that it appears @andrewash  is always returning _something_ from that endpoint, except when they manually handled the response, in which case calling `this.done()` should suffice. So without a sample repo or detailed repro steps to test this against, it's difficult to tell. If your suggested fix works, that's awesome, but I'd like to get to the bottom of it because that's not the intended behavior. Calling `this.done()` should skip the check for an empty endpoint response, and allow you to proceed without error.

**Comment by mehar** [comment]
@kahmali Reproduction steps are quite simple
1) Define an endpoint
2) Handle the response by yourself by not returning anything but by do end with this.done()

You will see the above mentioned exception

Add a return {}; statement at the end and see everything works as expected

**Comment by kahmali** [comment]
Alright. I'll test that out asap. As you can see there is an automated test in place for this that is passing in local and CI tests: https://github.com/kahmali/meteor-restivus/blob/devel/test/api_tests.coffee#L229. Not sure how that's possible, but I'll look into as soon as I have a chance. Thanks for providing the repro steps @mehar!

**Comment by kahmali** [comment]
Oh, I see. It _works_, but it still throws the error on the console. Ahhh. That should be an easy fix. I'll look into that. Sorry for the misunderstanding.

**Comment by mehar** [comment]
Thanks @kahmali , btw thanks for the awesome library!!!

**Comment by isdzulqor** [comment]
How to do this in restivus,, I wanna make a server for handling a file upload from my android native client. Below is the code that's implemented in node js that i get from tutorial in internet. How to do like this below in meteor js especially with this library restivus
Thank you
[New Text Document.txt](https://github.com/kahmali/meteor-restivus/files/51464/New.Text.Document.txt)

**Comment by a4xrbj1** [comment]
Same problem here (`Error: Cannot return null or undefined from an endpoint`), it's just that I'm trying to return statusCode 401. I've tried it like this:

    if (err) {
                    return {
                        statusCode: 401
                    };
                } else {
                    return {
                        statusCode: 200,
                        body: {status: 'success', message: 'Ok'}
                    };
                }

The statusCode 200 goes through without problems at all.

Detailed error message is:

    Error: Cannot return null or undefined from an endpoint: post api/login/2
    at Route.Route.addToApi._.each.JsonRoutes.add.responseData.status (packages/nimble:restivus/lib/route.coffee:61:25)
    at JsonRoutes.add (packages/simple:json-routes/json-routes.js:45:1)

Not sure if it's the same bug causing it. I've also tried it with returning a statusCode and an Object (similar to statusCode 200 object) but to no avail.

**Comment by kahmali** [comment]
Hi @a4xrbj1,

I probably did it trying to enforce "best practices," but you're required to return a `body` alongside any `statusCode` or `headers`. If anyone would like to submit a PR with the requirement removed, I'd gladly accept that. In the meantime, just add an empty `body` (string or object) in your error response. So your code should look like:

    if (err) {
                    return {
                        statusCode: 401,
                        body: {}
                    };
                } else {
                    return {
                        statusCode: 200,
                        body: {status: 'success', message: 'Ok'}
                    };
                }

I believe it's best practice to return an error message in the body in error responses, but to each their own. I'd personally suggest returning something like this (to follow the [JSend response standard](https://labs.omniti.com/labs/jsend) we use throughout Restivus, for consistent response format):

    if (err) {
                    return {
                        statusCode: 401,
                        body: {status: 'error', message: 'Unauthorized'}
                    };
                } else {
                    return {
                        statusCode: 200,
                        body: {status: 'success', message: 'Ok'}
                    };
                }

Hope that helps!

**Comment by LaughingBubba** [comment]
Hi there, I get the same issue when uploading. I'm trying to use the multer npm package with restivus to add a file upload function to some restful api. 

The irony is that although restivus throws an error the file does get uploaded!

I get this:
    '(STDERR) Error: Cannot return null or undefined from an endpoint: post api/uploads/
    (STDERR)     at packages/nimble_restivus/lib/route.coffee:61:25 
    (STDERR)     at packages/simple_json-routes/json-routes.js:76:1

If I add a return {} then the there's no error but then multer hangs. I've made a quick and dirty repo to demonstrate: https://github.com/LaughingBubba/uploads-meteor

Thoughts?

Cheers

**Comment by kahmali** [comment]
Hi @LaughingBubba,

Sorry to you and everyone else for the delay on fixing this. I completely overlooked it. I just published v0.8.11 to address the issue outlined by @mehar above. Hopefully that fixes the hanging in multer for you. I didn't have time to write a new test, so I'm going to keep this issue until you verify that it works for you. Thanks for reporting your issue, and sorry again to you and anyone else that's been waiting on this fix!

**Comment by LaughingBubba** [comment]
No worries! Thanks for the update. I'll check now and let you know.
