### ISSUE TITLE
Error: Can't set headers after they are sent.

### ISSUE THREAD

**Issue by sschuchlenz** [kahmali/meteor-restivus#144]
I've created two different APIs - one for JSON and one for XML data:

    # JSON API
    ApiJSONV1 = new Restivus
      version: 'json/v1'
      useDefaultAuth: false
      prettyJson: true

    # XML API
    ApiXMLV1 = new Restivus
      version: 'xml/v1'
      useDefaultAuth: false
      defaultHeaders:
        'Content-Type': 'application/xml'

The JSON part works fine but when I try to access the XML API endpoint (which returns exactly the same data as the JSON API), I get the console error

    Error: Can't set headers after they are sent.
    W20151013-13:28:11.753(2)? (STDERR)     at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    W20151013-13:28:11.753(2)? (STDERR)     at ServerResponse.res.setHeader (/home/schu/.meteor/packages/webapp/.1.2.2.wzn1ib++os+web.browser+web.cordova/npm/node_modules/connect/lib/patch.js:59:22)
    W20151013-13:28:11.753(2)? (STDERR)     at packages/simple_json-routes/packages/simple_json-routes.js:148:1
    W20151013-13:28:11.753(2)? (STDERR)     at Function._.each._.forEach (packages/underscore/packages/underscore.js:142:1)
    W20151013-13:28:11.754(2)? (STDERR)     at setHeaders (packages/simple_json-routes/packages/simple_json-routes.js:147:1)
    W20151013-13:28:11.754(2)? (STDERR)     at Object.JsonRoutes.sendError (packages/simple_json-routes/packages/simple_json-routes.js:128:1)
    W20151013-13:28:11.754(2)? (STDERR)     at packages/simple_json-routes/packages/simple_json-routes.js:55:1

Restivus & meteor are at the latest available versions.

**Comment by kahmali** [comment]
I'm so sorry for the ridiculously delayed response. Are you able to post the code for the XML endpoint? Are you manually sending the response from the endpoint without calling `this.done()`? That's the typical offender. I promise I'll respond a lot quicker when you get back. Again, sorry for the delay. I've just been caught up with a million other things.

**Comment by gauravraj** [comment]
I'm also getting the same error. I'm trying to integrate the payment gateway to my POST api and return html message. My api is declared something like this - 
```
var ApiV1 = new Restivus({
        apiPath: 'api/',
        defaultHeaders: {
            'Content-Type':'text/html'
        },
        prettyJson: false,
        useDefaultAuth: true
    });

ApiV1.addRoute('transactionStatus', {authRequired: false}, {
        post: {
             action: function() {
                         return "Some html table";
             }
     });

```
When my payment gateway redirects to this post api, I get the following error. 
```
Error: Can't set headers after they are sent.
    at ServerResponse.OutgoingMessage.setHeader (http.js:690:11)
    at ServerResponse.res.setHeader (/mnt/app/programs/server/npm/webapp/node_modules/connect/lib/patch.js:59:22)
    at packages/simple_json-routes/packages/simple_json-routes.js:148:1
    at Function._.each._.forEach (packages/underscore/underscore.js:113:1)
    at setHeaders (packages/simple_json-routes/packages/simple_json-routes.js:147:1)
    at Object.JsonRoutes.sendError (packages/simple_json-routes/packages/simple_json-routes.js:128:1)
    at packages/simple_json-routes/packages/simple_json-routes.js:55:1
```
But when I test the api using my rest client or a simple form submit, this works perfectly fine. What could be the issue here?
