### ISSUE TITLE
Async code in an api call

### ISSUE THREAD

**Issue by dheerajbhaskar** [kahmali/meteor-restivus#161]
## Context
I'm doing this in a game to give all players the same time window to make an action.

## Aim:
I want to be able to call an api which will countdown 30 seconds. 
More specifically: It will set value of 30 in a field in a document and update it to 29, 28, ..., 0.

## Problem:
The timer keeps getting stuck as witnessed on client i.e. it will countdown from 30 to (say) 25 properly and then gets stuck i.e. it will stay at 25, then after 10 seconds it will resume from 15 to 0. I've setup a subscription to notice these updates on client. I just want it to be fluid, and predictably count from 30 to 0. A lot of clients will be observing this to have the same time window to take an action; though in testing, no more than 2-3 clients have subscribed at the same time.

**The issue is:** I don't know if I'm doing it wrong (more likely), or it's something to do with restivus/using restivus, or something entirely different.

You might see some fencing `if (gameDoc.timer_value !== 0) {` because for some reason, even when I call this endpoint only once, it seems to run multiple times. For example: I used to see sequences like 30, 29, 28, 27, ..., 16, 30, 29, 28, 15, 14, ..., 0, -1, -2, -3, -4, -5, -6, 0 (it would stop at 0)

## Code
    function roundTimer(gameId, callback) {
      var gameDoc = Games_collection.findOne({_id: gameId});
      if (gameDoc.timer_value !== 0) {
        //FIXME console is not defined here
        //Error: cconsole is not defined
        //W20151118-15:17:21.258(5.5)? (STDERR)     at Route.Route._callEndpoint (packages/nimble_restivus/packages/nimble_restivus.js:318:1)
        //W20151118-15:17:21.255(5.5)? (STDERR) Error inside the Async.runSync: cconsole is not defined
        //W20151118-15:17:21.258(5.5)? (STDERR)     at Object.api.addRoute.get.action (server/api.js:55:1)
        //W20151118-15:17:21.258(5.5)? (STDERR)     at Async.wrap (packages/meteorhacks_async/packages/meteorhacks_async.js:79:1)
        //W20151118-15:17:21.259(5.5)? (STDERR)     at Route.Route.addToApi._.each.JsonRoutes.add.responseData.status (packages/nimble_restivus/packages/nimble_re
        //stivus.js:209:1)
        //W20151118-15:17:21.259(5.5)? (STDERR)     at JsonRoutes.add (packages/simple_json-routes/packages/simple_json-routes.js:53:1)
    
        //cconsole.log("skipping timer because timer=" + gameDoc.timer_value);
        return;
      }
    
    
      var timer = 30;
      Games_collection.update({_id: gameId}, {$set: {timer_value: timer}});
    
      var interval = Meteor.setInterval(function () {
    
        timer--;
        console.log('timer=' + timer + " gameId=" + gameId);
        Games_collection.update({_id: gameId}, {$inc: {timer_value: -1}});
    
        if (timer <= 0) {
          Meteor.clearInterval(interval);
          interval = 0;
          Games_collection.update({_id: gameId}, {$set: {timer_value: 0}});
          callback(null, 'okay');
        }
      }, 1000);
    }
    
    var wrappedDelayedMessage = Async.wrap(roundTimer);
    
    
    api.addRoute('start_timer_for_game/:id', {authRequired: false}, {
      get: {
        action: function () {
          //var timer    = 30;
          var gameId = this.urlParams.id;
          logVar("gameId", gameId);
    
    
          wrappedDelayedMessage(gameId);
    
          //Games_collection.update({_id: gameId}, {$set: {timer_value: timer}});
          //var interval = Meteor.setInterval(function () {
          //
          //  timer--;
          //  Games_collection.update({_id: gameId}, {$inc: {timer_value: -1}});
          //
          //  if (timer === 0) {
          //    Meteor.clearInterval(interval);
          //    Games_collection.update({_id: gameId}, {$set: {timer_value: 0}});
          //  }
          //}, 1000);
          return {status: 'success'};
          //return;
        }
      }
    });

**Comment by dheerajbhaskar** [comment]
I've also [asked this on SO](http://stackoverflow.com/questions/34489869/async-code-in-meteor-restivus-an-api-call), 'cause I'm not sure what's wrong here.
