### ISSUE TITLE
Custom route (get) throws error "TypeError: Cannot read property 'body' of undefined"

### ISSUE THREAD

**Issue by plugisto** [kahmali/meteor-restivus#17]
I run a very basic setup.
When I make a  "GET" call I always get this error "TypeError: Cannot read property 'body' of undefined".
Here is my code:

```
Devices = new Mongo.Collection('devices');

// API must be configured and built after startup!
if(Meteor.isServer) {
Meteor.startup(function () {

  // Global configuration
  Restivus.configure({
    useAuth: false,
    prettyJson: true
  });


  Restivus.addRoute('devices', {
    get: function () {
      console.log("GET fired");
    }
  });
});
}
```

Error message
```
I20150309-14:08:57.145(1)? GET fired
W20150309-14:08:57.201(1)? (STDERR) TypeError: Cannot read property 'body' of undefined
W20150309-14:08:57.201(1)? (STDERR)     at [object Object].Router.route.action (packages/nimble:restivus/lib/route.coffee:53:24)
W20150309-14:08:57.201(1)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
W20150309-14:08:57.201(1)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
W20150309-14:08:57.202(1)? (STDERR)     at packages/meteor/dynamics_nodejs.js:121:1
W20150309-14:08:57.202(1)? (STDERR)     at [object Object].urlencodedParser (/Users/bb/.meteor/packages/iron_router/.1.0.7.j8ckia++os+web.browser+web.cordova/npm/node_modules/body-parser/lib/types/urlencoded.js:72:36)
W20150309-14:08:57.202(1)? (STDERR)     at packages/iron:router/lib/router.js:277:1
W20150309-14:08:57.202(1)? (STDERR)     at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
W20150309-14:08:57.202(1)? (STDERR)     at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)
W20150309-14:08:57.202(1)? (STDERR)     at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
W20150309-14:08:57.202(1)? (STDERR)     at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
```

**Comment by plugisto** [comment]
Ok, got It.
This was because the "GET" function didn't return a response object.
When I add this everything works fine.

```
Restivus.addRoute('devices', {
    get: function () {
      console.log("GET fired");

      return {
          statusCode: 200,
          headers: {
            "Content-Type": "text/json",
            "X-Custom-Header": "custom value"
          },
          body: {
            status: "success",
            data: {
              "update": "everything is fine"
            }
          }
        };

    }
  });
```

**Comment by kahmali** [comment]
You should not have to return any status code and headers in your response. When you omit them, the defaults should be applied, but you should be able to return without those (which I'm doing in many of my own endpoints). My guess is that it was just the fact that you weren't returning _anything at all_ from that first endpoint. Try this instead:

```
Restivus.addRoute('devices', {
    get: function () {
      console.log("GET fired");
      return {
        status: "success",
        data: {
          "update": "everything is fine"
        }
      };
    }
  });
```

**Comment by kahmali** [comment]
I've tested this out multiple times and it works. You have to make sure that you return _something_ from an endpoint. I think I will add something to the docs to make this clearer, and try to add a better error response if possible. Let me know if it doesn't work for you for some reason. I will keep this issue open until a decision is made on the updates.
