### ISSUE TITLE
Converting circular structure to JSON

### ISSUE THREAD

**Issue by achirkof** [kahmali/meteor-restivus#240]
Hello @kahmali !
I'm trying to filtering result of `get` endpoind, but receive error.
I have enabled `useDefaultAuth` and get Id and token after successful authorisation.
```javascript
// REST API configuration

var Api = new Restivus({
    useDefaultAuth: true,
    prettyJson: true
});

Api.addRoute('workouts', {authRequired: true}, {
    get: {
    |   authRequired: true,
    |   action: function() {
    |   |   var workouts = Workouts.find({
    |   |   |   $or: [{
    |   |   |   |   createdBy: this.userId,
    |   |   |   |   isPrivate: true
    |   |   |   }, {
    |   |   |   |   isPrivate: false
    |   |   |   }],
    |   |   |   $and: [{
    |   |   |   |   isDeleted: false
    |   |   |   }]
    |   |   });
    |   |   return {status: 'success', data: workouts};
    |   }
    }
});
```

Before access to data I have to authorize
```
[andrey@smartworkout:~]% curl http://smartworkout.ru:3000/api/login -d "username=user2@m.com&password=111"
{
  "status": "success",
  "data": {
    "authToken": "W3SJbBG2gFP4KCyNJRP5ptbFq9sjuzW1S_zuk6YKH-Z",
    "userId": "QhKCfojmdC3Ep2oSz"
  }
}%
```

and after try to get data but get an error
```
[andrey@smartworkout:~]% curl -H "X-Auth-Token: W3SJbBG2gFP4KCyNJRP5ptbFq9sjuzW1S_zuk6YKH-Z" -H "X-User-Id: QhKCfojmdC3Ep2oSz" http://smartworkout.ru:3000/api/workouts/
TypeError: Converting circular structure to JSON<br> &nbsp; &nbsp;at Object.stringify (native)<br> &nbsp; &nbsp;at Object.stringify (/home/andrey/.meteor/packages/ecmascript-runtime/.0.2.11.16sx0wk++os+web.browser+web.cordova/npm/node_modules/meteor-ecmascript-runtime/node_modules/core-js/modules/es6.symbol.js:127:21)<br> &nbsp; &nbsp;at Route.share.Route.Route._respond (packages/nimble_restivus/lib/route.coffee:227:21)<br> &nbsp; &nbsp;at packages/nimble_restivus/lib/route.coffee:79:18<br> &nbsp; &nbsp;at packages/simple_json-routes/json-routes.js:76:1
```

Could you help me understand why?

If I try to simplify task and try to get data using standard endpoint it works fine.

```javascript
Api.addCollection(Workouts, {
    routeOptions: {
    |   authRequired: true
    }
});
```

I have read all issues regarding filterind endpoint data and didn't find any good example how to accomplish it. Is it possible to get data filtered for example by creation user or document status etc.?

**Comment by achirkof** [comment]
Ok. I found the cause of problem. It was in my request which return cursor instead of array. To get the array I have to add `fetch()` to my request.
Finally it should looks like:
```javascript
Api.addRoute('workouts', {authRequired: true}, {
    get: {
    |   authRequired: true,
    |   action: function() {
    |   |   var workouts = Workouts.find({
    |   |   |   $or: [{
    |   |   |   |   createdBy: this.userId,
    |   |   |   |   isPrivate: true
    |   |   |   }, {
    |   |   |   |   isPrivate: false
    |   |   |   }],
    |   |   |   $and: [{
    |   |   |   |   isDeleted: false
    |   |   |   }]
    |   |   }).fetch();  // here the convert cursor to array
    |   |   return {status: 'success', data: workouts};
    |   }
    }
});
```
