### ISSUE TITLE
Impossible to deploy Application

### ISSUE THREAD

**Issue by anshul-budhiraja** [kahmali/meteor-restivus#248]
@kahmali 
After adding this plugin. It is impossible to deploy the application.
Meteor version 1.2.1

**Comment by anshul-budhiraja** [comment]
Here are the logs

Error: Could not load the bindings file. Tried:
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Debug/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/Release/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Debug/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Debug/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/out/Release/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/Release/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/build/default/bcrypt_lib.node
 → /opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/compiled/0.12.5/linux/x64/bcrypt_lib.node
    at bindings (/opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/node_modules/bindings/bindings.js:84:13)
    at Object.<anonymous> (/opt/meteor/app/programs/server/npm/npm-bcrypt/node_modules/bcrypt/bcrypt.js:3:35)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.Npm.require (/opt/meteor/app/programs/server/boot.js:162:18)
    at packages/npm-bcrypt/packages/npm-bcrypt.js:9:1
[xx.xx.xx.xx] error: Forever detected script exited with code: 1
[xx.xx.xx.xx] error: Script restart attempt #27

**Comment by anshul-budhiraja** [comment]
Updating the mup version resolved  my issue.

**Comment by kahmali** [comment]
Thanks for updating with your solution @anshul-budhiraja!
