### ISSUE TITLE
TypeError: Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by mryraghi** [kahmali/meteor-restivus#259]
I came across this error today and Meteor won't even start.

```bash
TypeError: Cannot read property 'call' of undefined
at Restivus.<anonymous> (packages/nimble_restivus/lib/auth.coffee:41:27)
at Array.forEach (native)
at Function._.each._.forEach (packages/underscore.js:139:11)
at Restivus.Assets.Restivus.Restivus.addCollection (packages/nimble_restivus/lib/auth.coffee:41:27)
at meteorInstall.server.api.js (server/api.js:547:5)
```

#### api.js:547:5
```API.addCollection(Meteor.users, {...```

#### aut.coffee:41:27
```coffeescript 
###
  Log a user in with their password
###
@Auth.loginWithPassword = (user, password) ->
  if not user or not password
    throw new Meteor.Error 401, 'Unauthorized'
```

accounts-password already updated to 1.3.3.

Any ideas?

**Comment by mryraghi** [comment]
To be honest, this is blocking all my API and this is no good. 
Could you please help?

**Comment by anthonymanzo** [comment]
Same problem here

**Comment by cunnagin** [comment]
Same issue for me

**Comment by jykae** [comment]
Noticed same issue when previously worked with restivus-swagger plugin, forked without latest PRs. Switching possibly back if gets fixed.

**Comment by TristanWiley** [comment]
Same  here, it seemed to occur after I updated Meteor.

**Comment by TristanWiley** [comment]
Temporarily fixed by downgrading to version 0.8.11

`meteor add nimble:restivus@=0.8.11`

**Comment by vauruk** [comment]
Same error. But after update meteor 1.4.3.2. thanks

**Comment by gurjit03** [comment]
Any solution guys ? same for me as well and I am on meteor 1.4.3.2 .

**Edit** : Got it fixed using **_excludedEndpoints: [ 'put','delete','patch']_**

**Comment by ujwal-setlur** [comment]
@gurjit03 this worked, but why should this matter?

```  excludedEndpoints: ["patch"]```

worked for me. So, patch operation is not allowed?

**Comment by ujwal-setlur** [comment]
@TristanWiley downgrading to 0.8.11 worked for me as well.

**Comment by nosizejosh** [comment]
I think this issue is related to https://github.com/kahmali/meteor-restivus/issues/262
