### ISSUE TITLE
Getting server error when I try to connect to login endpoint

### ISSUE THREAD

**Issue by dovrosenberg** [kahmali/meteor-restivus#5]
Hello.

Everything works great before I turn on authentication.  But when I attempt to connect to the login endpoint as follows, I get an error.

I'm doing a POST to 
`http://localhost:3000/api/login` 
with a body of
`password=xyz&user=abc`   

The server generates the following response (which comes back to the client and is also generated from the meteor server in the command window):
>TypeError: Cannot call method 'indexOf' of undefined
    at [object Object].add.post (packages/nimble:restivus/lib/restivus.coffee:73:29)
    at [object Object].Route._callEndpoint (packages/nimble:restivus/lib/route.coffee:121:25)
    at [object Object].Router.route.action (packages/nimble:restivus/lib/route.coffee:40:40)
    at boundNext (packages/iron:middleware-stack/lib/middleware_stack.js:251:1)
    at runWithEnvironment (packages/meteor/dynamics_nodejs.js:108:1)
    at packages/meteor/dynamics_nodejs.js:121:1
    at [object Object].urlencodedParser (H:\ventureTrack\.meteor\local\build\programs\server\npm\iron_router\node_modules\body-parser\lib\types\urlencoded.js:72:36)
    at packages/iron:router/lib/router.js:277:1
    at [object Object]._.extend.withValue (packages/meteor/dynamics_nodejs.js:56:1)
    at [object Object].hookWithOptions (packages/iron:router/lib/router.js:276:1)

Any ideas?  I have set useAuth to true in the configure block.

Thanks!

**Comment by kahmali** [comment]
Is that your exact body? Because all of those keys and values should be strings. Just want to make sure before I go trying to reproduce the issue.

**Comment by dovrosenberg** [comment]
That is the exact body.  Is that not the right format?

I did try various other combinations of quoting, as well.  Same result with all of them...

**Comment by dovrosenberg** [comment]
I'm sorry... I'm an idiot.  I wasn't setting the Content-Type appropriately.  Set it to "application/x-www-form-urlencoded" and everything worked.  Sorry!

**Comment by kahmali** [comment]
Oh, sorry about that. The default content type in Restivus is text/json (it may change to application/json eventually). I need to make sure I mention that in the docs.

**Comment by kahmali** [comment]
Okay, it is mentioned in the docs, in the [Response Data](https://github.com/kahmali/meteor-restivus#response-data) section. I'll see what I can do to make sure that information is displayed more prominently.

**Comment by dovrosenberg** [comment]
Just to be clear, my issue was the reverse direction.  I wasn’t setting the content type on my request, which was causing the server to throw an error when it got it.

     - Dov
